version: '3'
services:
  db:
    image: postgres:10.4
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    expose:
    - 5432
    ports:
    - 5432:5432
